// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrJ4aQ26XXITiKQpHnRMFzo2NfaUu2O8c',
    appId: '1:83127338671:web:6b566d70ff9ee3aed3b65a',
    messagingSenderId: '83127338671',
    projectId: 'ascendia-app-final',
    authDomain: 'ascendia-app-final.firebaseapp.com',
    storageBucket: 'ascendia-app-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsuWIyi51-Zhan8dDIOzU8Ha90xsRVCFg',
    appId: '1:83127338671:android:bf7fb2565fb00689d3b65a',
    messagingSenderId: '83127338671',
    projectId: 'ascendia-app-final',
    storageBucket: 'ascendia-app-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxXauiMVfdBnWvcdBXDWCtND4OkK-yoFk',
    appId: '1:83127338671:ios:51fd3db01d24469bd3b65a',
    messagingSenderId: '83127338671',
    projectId: 'ascendia-app-final',
    storageBucket: 'ascendia-app-final.firebasestorage.app',
    iosBundleId: 'com.carlo.ascendia',
  );

}