import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart'; // generated by flutterfire configure
import 'data/services/premium_service.dart';

import 'features/auth/login_screen.dart';
import 'features/feed/feed_screen.dart';
import 'features/profile/presentation/profile_screen.dart';
import 'features/guilds/guilds_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  
  // Initialize RevenueCat
  final premiumService = PremiumService();
  await premiumService.init();
  
  runApp(
    ProviderScope(
      child: const AscendiaApp(),
    ),
  );
}

class AscendiaApp extends ConsumerWidget {
  const AscendiaApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      title: 'Ascendia',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: Colors.deepPurple,
        brightness: Brightness.light,
        useMaterial3: true,
      ),
      darkTheme: ThemeData(
        colorSchemeSeed: Colors.deepPurple,
        brightness: Brightness.dark,
        useMaterial3: true,
      ),
      initialRoute: '/login',
      routes: {
        '/login': (_) => const LoginScreen(),
        '/feed': (_) => const FeedScreen(),
        '/profile': (_) => const ProfileScreen(),
        '/guilds': (_) => const GuildsScreen(),
      },
    );
  }
}
